services:
  postgres:
    container_name: order-service
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

    restart: always

  inventory:
    container_name: inventory-service
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_INVENTORY_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5555:5432"

    restart: always