server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
spring:

  datasource:
    url: jdbc:postgresql://localhost:5444/order-service
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

logging:
  level:
    org.hibernate.jpa: DEBUG